import { useState, useEffect, useRef } from "react";

// ─── Data ─────────────────────────────────────────────────────────────────────

const NAV_LINKS = [
  { label: "Skills", href: "#skills" },
  { label: "Projects", href: "#projects" },
  { label: "Learning", href: "#learning" },
  { label: "Contact", href: "#contact" },
];

const SKILL_DOMAINS = [
  {
    id: "detection",
    label: "Threat Detection & Telemetry",
    icon: "◈",
    color: "emerald",
    skills: [
      { name: "Sysmon (Advanced Endpoint Logging)", level: 75 },
      { name: "Wireshark / Telemetry Analysis", level: 68 },
      { name: "Indicators of Compromise (IoCs)", level: 70 },
      { name: "Social-Engineer Toolkit (SET) Simulation", level: 65 },
      { name: "Incident Response Fundamentals", level: 60 },
    ],
  },
  {
    id: "systems",
    label: "Networking & Systems",
    icon: "⬡",
    color: "emerald",
    skills: [
      { name: "Cisco Packet Tracer (VLANs, ACLs, Routing)", level: 72 },
      { name: "Network Protocols (TCP/IP, DNS, DHCP)", level: 70 },
      { name: "Linux (Kali / Parrot Security)", level: 68 },
      { name: "Windows 10/11 Administration", level: 78 },
      { name: "Virtualisation (UTM / Sandbox Labs)", level: 74 },
    ],
  },
  {
    id: "scripting",
    label: "Scripting & Compliance",
    icon: "⟩_",
    color: "cyan",
    skills: [
      { name: "Python", level: 58 },
      { name: "SQL", level: 62 },
      { name: "Systems Hardening", level: 65 },
      { name: "Access Control (IAM)", level: 60 },
      { name: "Data Governance (GDPR)", level: 80 },
    ],
  },
];

const PROJECTS = [
  {
    tier: 1,
    label: "FLAGSHIP — TM470",
    accentColor: "emerald",
    title: "Evaluating Host-Based Telemetry (Sysmon) for the Detection of SET-Automated Credential Harvesting on Windows 11",
    subtitle: "UTM · Parrot Security · Sysmon · Windows 11 · Social-Engineer Toolkit (SET)",
    problem:
      "Standard corporate email gateways regularly fail to intercept highly tailored, AI-generated social engineering attacks, moving the defensive perimeter down to endpoint log telemetry.",
    architecture:
      "Isolated virtualisation sandbox built in UTM: a Parrot Security attacker node targeting a Windows 11 endpoint, deliberately configured without enterprise-grade security tooling to establish a realistic, resource-constrained baseline.",
    implementation: [
      "Used the Social-Engineer Toolkit (SET) to execute credential-harvesting attacks against the Windows 11 target",
      "Deployed Sysmon on the victim endpoint with a hardened logging configuration to capture process creation and network connection events",
      "Correlated captured telemetry to isolate the specific indicators of compromise (IoCs) generated by SET's attack chain",
      "Authored a Hardened Logging Guide and IoC Blueprint to give resource-constrained organisations a baseline endpoint-visibility playbook",
    ],
    result:
      "Successfully isolated critical IoCs generated by the SET attack chain and produced reusable Sysmon configuration guidance for organisations without budget for full enterprise EDR tooling.",
    github: "https://github.com/elbmichael/sysmon-set-credential-harvest-detection",
    tags: ["Sysmon", "SET", "Windows 11", "UTM", "Parrot Security", "IoC Analysis"],
  },
  {
    tier: 2,
    label: "NETWORK LAB — TM257/TM357",
    accentColor: "cyan",
    title: "Enterprise Network Routing & Switching Lab",
    subtitle: "Cisco Packet Tracer · VLANs · ACLs · Inter-VLAN Routing",
    problem:
      "Modern enterprise networks require scalable, resilient, and secure architecture to prevent broadcast storms and unauthorised cross-department access.",
    architecture:
      "Multi-site enterprise network simulated in Cisco Packet Tracer as part of the Open University's CCNA-aligned modules (TM257/TM357).",
    implementation: [
      "Structured IPv4/IPv6 addressing schemes across multiple simulated sites",
      "Implemented VLAN segmentation and configured inter-VLAN routing",
      "Applied Access Control Lists (ACLs) to restrict traffic between segments",
      "Diagnosed routing anomalies using CLI verification commands",
    ],
    result:
      "Built a functional, secure network simulation that optimised data flow and restricted lateral movement across subnet boundaries.",
    github: "https://github.com/elbmichael/enterprise-network-lab",
    tags: ["Cisco Packet Tracer", "VLAN", "ACL", "Routing & Switching"],
  },
];

const CERTS = [
  { name: "BSc (Hons) Cybersecurity — The Open University", status: "Active", icon: "◈", color: "emerald", eta: "Expected graduation: 2026" },
  { name: "Diploma of Higher Education in Cyber Security", status: "Completed", icon: "✓", color: "emerald", eta: "2025" },
  { name: "Certificate of Higher Education in Computing and IT", status: "Completed", icon: "✓", color: "cyan", eta: "2023" },
  { name: "Pearson BTEC Level 3 National Diploma in IT", status: "Completed", icon: "✓", color: "cyan", eta: "Leeds City College, 2017–2019" },
];

// ─── Components ───────────────────────────────────────────────────────────────

function NavBar() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 40);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <nav
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 100,
        borderBottom: scrolled ? "1px solid rgba(30,58,95,0.8)" : "1px solid transparent",
        background: scrolled ? "rgba(15,23,42,0.92)" : "transparent",
        backdropFilter: scrolled ? "blur(12px)" : "none",
        transition: "all 0.3s ease",
      }}
    >
      <div style={{ maxWidth: "1200px", margin: "0 auto", padding: "0 24px", display: "flex", alignItems: "center", justifyContent: "space-between", height: "60px" }}>
        <span className="font-mono" style={{ color: "#f59e0b", fontSize: "0.85rem", letterSpacing: "0.1em" }}>
          <span style={{ color: "#7a7060" }}>~/</span>portfolio<span className="cursor-blink" style={{ color: "#f59e0b" }}>_</span>
        </span>

        {/* Desktop nav */}
        <div style={{ display: "flex", gap: "32px", alignItems: "center" }} className="hidden-mobile">
          {NAV_LINKS.map((l) => (
            <a
              key={l.href}
              href={l.href}
              className="font-mono"
              style={{
                color: "#7a7060",
                fontSize: "0.78rem",
                letterSpacing: "0.12em",
                textTransform: "uppercase",
                textDecoration: "none",
                transition: "color 0.2s",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.color = "#f59e0b")}
              onMouseLeave={(e) => (e.currentTarget.style.color = "#7a7060")}
            >
              {l.label}
            </a>
          ))}
          <a
            href="#contact"
            style={{
              padding: "6px 16px",
              border: "1px solid #f59e0b",
              color: "#f59e0b",
              fontSize: "0.78rem",
              fontFamily: "'JetBrains Mono', monospace",
              letterSpacing: "0.12em",
              textDecoration: "none",
              textTransform: "uppercase",
              transition: "all 0.2s",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = "#f59e0b";
              e.currentTarget.style.color = "#12100c";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = "transparent";
              e.currentTarget.style.color = "#f59e0b";
            }}
          >
            Hire Me
          </a>
        </div>

        {/* Mobile hamburger */}
        <button
          onClick={() => setMenuOpen(!menuOpen)}
          className="show-mobile"
          style={{ background: "none", border: "none", color: "#f59e0b", cursor: "pointer", fontSize: "1.2rem" }}
        >
          {menuOpen ? "✕" : "☰"}
        </button>
      </div>

      {/* Mobile menu */}
      {menuOpen && (
        <div style={{ background: "#12100c", borderTop: "1px solid #2e2a20", padding: "16px 24px" }}>
          {NAV_LINKS.map((l) => (
            <a
              key={l.href}
              href={l.href}
              onClick={() => setMenuOpen(false)}
              className="font-mono"
              style={{ display: "block", color: "#a89880", fontSize: "0.85rem", padding: "10px 0", textDecoration: "none", borderBottom: "1px solid #221e16" }}
            >
              {l.label}
            </a>
          ))}
        </div>
      )}
    </nav>
  );
}

function HeroSection() {
  return (
    <section
      id="hero"
      className="grid-bg"
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        padding: "120px 24px 80px",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {/* Accent glow orb */}
      <div style={{
        position: "absolute",
        top: "20%",
        right: "10%",
        width: "400px",
        height: "400px",
        background: "radial-gradient(circle, rgba(251,146,60,0.07) 0%, transparent 70%)",
        pointerEvents: "none",
      }} />
      <div style={{
        position: "absolute",
        bottom: "10%",
        left: "5%",
        width: "300px",
        height: "300px",
        background: "radial-gradient(circle, rgba(245,158,11,0.06) 0%, transparent 70%)",
        pointerEvents: "none",
      }} />

      <div style={{ maxWidth: "1200px", margin: "0 auto", width: "100%" }}>
        {/* Status badge */}
        <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "32px" }}>
          <span
            className="pulse-dot"
            style={{
              width: "8px",
              height: "8px",
              borderRadius: "50%",
              background: "#f59e0b",
              display: "inline-block",
              boxShadow: "0 0 10px #f59e0b",
            }}
          />
          <span
            className="font-mono"
            style={{
              fontSize: "0.72rem",
              letterSpacing: "0.15em",
              textTransform: "uppercase",
              color: "#f59e0b",
              border: "1px solid rgba(16,185,129,0.25)",
              padding: "4px 12px",
            }}
          >
            Active — BSc Cybersecurity student, building endpoint detection labs
          </span>
        </div>

        {/* Main heading */}
        <div style={{ marginBottom: "24px" }}>
          <p className="font-mono" style={{ color: "#fb923c", fontSize: "0.82rem", letterSpacing: "0.2em", marginBottom: "12px", textTransform: "uppercase" }}>
            // Aspiring Cybersecurity Analyst
          </p>
          <h1
            className="font-display"
            style={{
              fontSize: "clamp(2.4rem, 7vw, 5.5rem)",
              fontWeight: 700,
              lineHeight: 0.95,
              letterSpacing: "-0.01em",
              color: "#f5efe4",
              margin: 0,
            }}
          >
            Michael{" "}
            <span className="glow-emerald" style={{ color: "#f59e0b" }}>
              Elboateng Manu
            </span>
          </h1>
          <h2
            className="font-display"
            style={{
              fontSize: "clamp(1.5rem, 4vw, 3rem)",
              fontWeight: 500,
              color: "#6b6457",
              margin: "8px 0 0",
              letterSpacing: "0.02em",
            }}
          >
            Blue Team · Endpoint Telemetry · Network Defense
          </h2>
        </div>

        {/* Value proposition */}
        <p
          style={{
            maxWidth: "580px",
            color: "#a89880",
            fontSize: "1.05rem",
            lineHeight: 1.7,
            marginBottom: "48px",
          }}
        >
          Aspiring cybersecurity analyst completing a BSc (Hons) in Cybersecurity at the
          Open University, with hands-on homelab experience in Sysmon-based endpoint
          detection, network architecture, and systems hardening. Bringing five years of
          fast-paced technical troubleshooting and stakeholder communication from IT
          support into a dedicated security role.
        </p>

        {/* CTAs */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: "14px", marginBottom: "64px" }}>
          <CtaButton href="#projects" primary>
            View Case Studies
          </CtaButton>
          <CtaButton href="/cv.pdf" download>
            Download CV
          </CtaButton>
          <CtaButton href="https://github.com/elbmichael" external icon="⌥ GitHub">
            GitHub
          </CtaButton>
          <CtaButton href="https://www.linkedin.com/in/michael-elboateng" external icon="⌥ LinkedIn">
            LinkedIn
          </CtaButton>
        </div>

        {/* Terminal stats strip */}
        <div
          className="font-mono"
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: "32px",
            paddingTop: "32px",
            borderTop: "1px solid #2e2a20",
          }}
        >
          {[
            { k: "DEGREE", v: "BSc Cybersecurity" },
            { k: "GRAD_YEAR", v: "2026" },
            { k: "CORE_PROJECTS", v: "2" },
            { k: "IT_SUPPORT_YRS", v: "5+" },
          ].map(({ k, v }) => (
            <div key={k}>
              <div style={{ fontSize: "0.65rem", color: "#6b6457", letterSpacing: "0.15em" }}>{k}</div>
              <div style={{ fontSize: "1.4rem", color: "#f59e0b", fontWeight: 700 }}>{v}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CtaButton({
  href,
  children,
  primary,
  download,
  external,
  icon,
}: {
  href: string;
  children: React.ReactNode;
  primary?: boolean;
  download?: boolean;
  external?: boolean;
  icon?: string;
}) {
  const baseStyle: React.CSSProperties = {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "0.8rem",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    textDecoration: "none",
    cursor: "pointer",
    transition: "all 0.2s ease",
    userSelect: "none",
  };

  const [hovered, setHovered] = useState(false);

  if (primary) {
    return (
      <a
        href={href}
        style={{
          ...baseStyle,
          background: hovered ? "#059669" : "#f59e0b",
          color: "#12100c",
          fontWeight: 700,
          boxShadow: hovered ? "0 0 24px rgba(16,185,129,0.4)" : "0 0 12px rgba(16,185,129,0.2)",
        }}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
      >
        {children}
      </a>
    );
  }

  return (
    <a
      href={href}
      target={external ? "_blank" : undefined}
      rel={external ? "noopener noreferrer" : undefined}
      download={download}
      style={{
        ...baseStyle,
        border: "1px solid",
        borderColor: hovered ? "#a89880" : "#3a3428",
        color: hovered ? "#f5efe4" : "#a89880",
        background: "transparent",
      }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {children}
    </a>
  );
}

function SkillMatrix() {
  const [active, setActive] = useState("detection");
  const domain = SKILL_DOMAINS.find((d) => d.id === active)!;

  return (
    <section id="skills" style={{ padding: "100px 24px", borderTop: "1px solid #2e2a20" }}>
      <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
        <SectionLabel>02 // Skills</SectionLabel>
        <h2
          className="font-display"
          style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", fontWeight: 700, marginBottom: "48px", color: "#f5efe4" }}
        >
          Capability Matrix
        </h2>

        {/* Domain tabs */}
        <div style={{ display: "flex", gap: "0", marginBottom: "48px", borderBottom: "1px solid #2e2a20" }}>
          {SKILL_DOMAINS.map((d) => (
            <button
              key={d.id}
              onClick={() => setActive(d.id)}
              className="font-mono"
              style={{
                padding: "12px 24px",
                border: "none",
                background: "none",
                cursor: "pointer",
                fontSize: "0.75rem",
                letterSpacing: "0.12em",
                textTransform: "uppercase",
                color: active === d.id ? (d.color === "emerald" ? "#f59e0b" : "#fb923c") : "#6b6457",
                borderBottom: active === d.id ? `2px solid ${d.color === "emerald" ? "#f59e0b" : "#fb923c"}` : "2px solid transparent",
                marginBottom: "-1px",
                transition: "all 0.2s",
              }}
            >
              <span style={{ marginRight: "8px" }}>{d.icon}</span>
              {d.label}
            </button>
          ))}
        </div>

        {/* Skill bars */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" }} className="skills-grid">
          {domain.skills.map((s) => (
            <SkillBar key={s.name} name={s.name} level={s.level} color={domain.color} />
          ))}
        </div>
      </div>
    </section>
  );
}

function SkillBar({ name, level, color }: { name: string; level: number; color: string }) {
  const accentColor = color === "emerald" ? "#f59e0b" : "#fb923c";
  const dimColor = color === "emerald" ? "rgba(16,185,129,0.12)" : "rgba(6,182,212,0.12)";

  return (
    <div style={{ padding: "16px", background: "#1c1914", border: "1px solid #2e2a20" }}>
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "10px" }}>
        <span style={{ fontSize: "0.88rem", color: "#d4c4a8" }}>{name}</span>
        <span className="font-mono" style={{ fontSize: "0.72rem", color: accentColor }}>{level}%</span>
      </div>
      <div style={{ height: "3px", background: "#221e16", position: "relative" }}>
        <div
          style={{
            height: "100%",
            width: `${level}%`,
            background: `linear-gradient(90deg, ${accentColor}, ${dimColor})`,
            boxShadow: `0 0 8px ${accentColor}44`,
          }}
        />
      </div>
    </div>
  );
}

function ProjectsSection() {
  const [filter, setFilter] = useState<number | null>(null);
  const flagships = PROJECTS.filter((p) => p.tier === 1);
  const labs = PROJECTS.filter((p) => p.tier === 2);

  return (
    <section id="projects" style={{ padding: "100px 24px", background: "#0e0c09", borderTop: "1px solid #2e2a20" }}>
      <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
        <SectionLabel>03 // Projects</SectionLabel>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: "24px", marginBottom: "48px" }}>
          <h2
            className="font-display"
            style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", fontWeight: 700, color: "#f5efe4", margin: 0 }}
          >
            Project Showcase
          </h2>
          <div style={{ display: "flex", gap: "8px" }}>
            {[null, 1, 2].map((t) => (
              <button
                key={String(t)}
                onClick={() => setFilter(t)}
                className="font-mono"
                style={{
                  padding: "6px 14px",
                  fontSize: "0.7rem",
                  letterSpacing: "0.12em",
                  textTransform: "uppercase",
                  background: filter === t ? "#f59e0b" : "transparent",
                  color: filter === t ? "#12100c" : "#6b6457",
                  border: "1px solid",
                  borderColor: filter === t ? "#f59e0b" : "#3a3428",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                {t === null ? "All" : `T${t}`}
              </button>
            ))}
          </div>
        </div>

        {/* Tier 1 — Flagship */}
        {(filter === null || filter === 1) && flagships.map((p) => (
          <FlagshipCard key={p.title} project={p} />
        ))}

        {/* Tier 2 — SOC Labs */}
        {(filter === null || filter === 2) && (
          <>
            <TierHeader tier={2} label="Network & SOC Labs" />
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px", marginBottom: "56px" }} className="two-col-grid">
              {labs.map((p) => <LabCard key={p.title} project={p} />)}
            </div>
          </>
        )}
      </div>
    </section>
  );
}

function TierHeader({ tier, label }: { tier: number; label: string }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: "16px", marginBottom: "24px", marginTop: "16px" }}>
      <span className="tier-badge" style={{ color: "#f59e0b", border: "1px solid rgba(16,185,129,0.3)", padding: "3px 10px" }}>
        TIER {tier}
      </span>
      <span className="font-display" style={{ fontSize: "1.1rem", color: "#7a7060", letterSpacing: "0.05em" }}>{label}</span>
      <div style={{ flex: 1, height: "1px", background: "#2e2a20" }} />
    </div>
  );
}

function FlagshipCard({ project: p }: { project: typeof PROJECTS[0] }) {
  const [open, setOpen] = useState(false);
  const accent = p.accentColor === "emerald" ? "#f59e0b" : "#fb923c";

  return (
    <div
      style={{
        border: `1px solid ${accent}44`,
        background: "#1c1914",
        marginBottom: "40px",
        boxShadow: `0 0 40px ${accent}0a`,
      }}
    >
      {/* Header */}
      <div
        style={{
          padding: "24px 28px",
          borderBottom: `1px solid ${accent}22`,
          background: `linear-gradient(135deg, #221e16 0%, #1c1914 100%)`,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          flexWrap: "wrap",
          gap: "16px",
        }}
      >
        <div>
          <span className="tier-badge" style={{ color: accent, marginBottom: "8px", display: "block" }}>
            ▶ TIER 1 // {p.label}
          </span>
          <h3 className="font-display" style={{ fontSize: "clamp(1.4rem, 3vw, 2rem)", fontWeight: 700, color: "#f5efe4", margin: 0 }}>
            {p.title}
          </h3>
          <p className="font-mono" style={{ fontSize: "0.72rem", color: "#6b6457", marginTop: "4px" }}>{p.subtitle}</p>
        </div>
        <div style={{ display: "flex", gap: "10px", flexWrap: "wrap" }}>
          {p.tags?.map((t) => (
            <span key={t} className="font-mono" style={{ fontSize: "0.65rem", letterSpacing: "0.1em", padding: "3px 8px", border: `1px solid ${accent}33`, color: accent }}>
              {t}
            </span>
          ))}
        </div>
      </div>

      {/* Body */}
      <div style={{ padding: "28px" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px", marginBottom: "24px" }} className="two-col-grid">
          <div>
            <CaseLabel>Problem Statement</CaseLabel>
            <p style={{ color: "#a89880", fontSize: "0.92rem", lineHeight: 1.7 }}>{p.problem}</p>
          </div>
          <div>
            <CaseLabel>Architecture</CaseLabel>
            <p style={{ color: "#a89880", fontSize: "0.92rem", lineHeight: 1.7 }}>{p.architecture}</p>
          </div>
        </div>

        <div style={{ marginBottom: "24px" }}>
          <CaseLabel>Defensive Implementation</CaseLabel>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }} className="two-col-grid">
            {p.implementation?.map((item, i) => (
              <div key={i} style={{ display: "flex", gap: "10px", padding: "10px 14px", background: "#12100c", border: "1px solid #2e2a20" }}>
                <span className="font-mono" style={{ color: accent, flexShrink: 0, fontSize: "0.75rem" }}>{`[${i + 1}]`}</span>
                <span style={{ color: "#d4c4a8", fontSize: "0.85rem", lineHeight: 1.5 }}>{item}</span>
              </div>
            ))}
          </div>
        </div>

        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "16px", paddingTop: "20px", borderTop: "1px solid #2e2a20" }}>
          <div>
            <CaseLabel>Result</CaseLabel>
            <p style={{ color: "#f5efe4", fontSize: "0.95rem", margin: 0 }}>
              <span style={{ color: accent }}>→ </span>{p.result}
            </p>
          </div>
          <a
            href={p.github}
            target="_blank"
            rel="noopener noreferrer"
            className="font-mono"
            style={{
              padding: "10px 20px",
              border: `1px solid ${accent}`,
              color: accent,
              textDecoration: "none",
              fontSize: "0.75rem",
              letterSpacing: "0.12em",
              textTransform: "uppercase",
              transition: "all 0.2s",
              display: "inline-block",
            }}
            onMouseEnter={(e) => { e.currentTarget.style.background = accent; e.currentTarget.style.color = "#12100c"; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; e.currentTarget.style.color = accent; }}
          >
            View Repository →
          </a>
        </div>
      </div>
    </div>
  );
}

function LabCard({ project: p }: { project: typeof PROJECTS[0] }) {
  const accent = p.accentColor === "emerald" ? "#f59e0b" : "#fb923c";

  return (
    <div className="card-lift" style={{ border: "1px solid #2e2a20", background: "#1c1914", padding: "24px" }}>
      <span className="tier-badge" style={{ color: accent, display: "block", marginBottom: "10px" }}>{p.label}</span>
      <h3 className="font-display" style={{ fontSize: "1.3rem", fontWeight: 700, color: "#f5efe4", marginBottom: "4px" }}>{p.title}</h3>
      <p className="font-mono" style={{ fontSize: "0.7rem", color: "#6b6457", marginBottom: "16px" }}>{p.subtitle}</p>
      <p style={{ fontSize: "0.85rem", color: "#7a7060", lineHeight: 1.6, marginBottom: "16px" }}>{p.problem}</p>
      <div style={{ marginBottom: "16px" }}>
        {p.implementation?.slice(0, 2).map((item, i) => (
          <div key={i} style={{ display: "flex", gap: "8px", marginBottom: "6px" }}>
            <span className="font-mono" style={{ color: accent, fontSize: "0.72rem", flexShrink: 0 }}>&gt;</span>
            <span style={{ color: "#a89880", fontSize: "0.82rem" }}>{item}</span>
          </div>
        ))}
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", paddingTop: "16px", borderTop: "1px solid #2e2a20" }}>
        <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
          {p.tags?.slice(0, 2).map((t) => (
            <span key={t} className="font-mono" style={{ fontSize: "0.62rem", padding: "2px 7px", border: `1px solid ${accent}33`, color: "#6b6457" }}>{t}</span>
          ))}
        </div>
        <a href={p.github} target="_blank" rel="noopener noreferrer" className="font-mono" style={{ fontSize: "0.7rem", color: accent, textDecoration: "none" }}>
          Repo →
        </a>
      </div>
    </div>
  );
}

function ToolCard({ project: p }: { project: typeof PROJECTS[0] }) {
  const accent = p.accentColor === "emerald" ? "#f59e0b" : "#fb923c";

  return (
    <div className="card-lift" style={{ border: "1px solid #2e2a20", background: "#1c1914", padding: "20px", display: "flex", flexDirection: "column" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "12px" }}>
        <h3 className="font-mono" style={{ fontSize: "0.95rem", color: "#f5efe4", fontWeight: 700 }}>{p.title}</h3>
        <span className="tier-badge" style={{ color: accent }}>T3</span>
      </div>
      <p className="font-mono" style={{ fontSize: "0.68rem", color: "#6b6457", marginBottom: "12px" }}>{p.subtitle}</p>
      <p style={{ fontSize: "0.82rem", color: "#7a7060", lineHeight: 1.6, flex: 1, marginBottom: "14px" }}>{p.desc}</p>
      <pre
        style={{
          background: "#0e0c09",
          border: "1px solid #2e2a20",
          padding: "10px",
          fontSize: "0.68rem",
          color: "#a89880",
          lineHeight: 1.5,
          overflow: "auto",
          marginBottom: "14px",
          fontFamily: "'JetBrains Mono', monospace",
          whiteSpace: "pre-wrap",
        }}
      >
        {p.snippet}
      </pre>
      <a
        href={p.github}
        target="_blank"
        rel="noopener noreferrer"
        className="font-mono"
        style={{
          display: "block",
          textAlign: "center",
          padding: "8px",
          border: `1px solid ${accent}55`,
          color: accent,
          fontSize: "0.7rem",
          letterSpacing: "0.1em",
          textDecoration: "none",
          transition: "all 0.2s",
        }}
        onMouseEnter={(e) => { e.currentTarget.style.background = `${accent}15`; }}
        onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; }}
      >
        Open Repository →
      </a>
    </div>
  );
}

function CaseLabel({ children }: { children: React.ReactNode }) {
  return (
    <p className="font-mono" style={{ fontSize: "0.65rem", letterSpacing: "0.18em", textTransform: "uppercase", color: "#6b6457", marginBottom: "8px", marginTop: 0 }}>
      {children}
    </p>
  );
}

function LearningSection() {
  return (
    <section id="learning" style={{ padding: "100px 24px", borderTop: "1px solid #2e2a20" }}>
      <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
        <SectionLabel>04 // Learning</SectionLabel>
        <h2
          className="font-display"
          style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", fontWeight: 700, marginBottom: "48px", color: "#f5efe4" }}
        >
          Continuous Learning
        </h2>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px" }} className="three-col-grid">
          {CERTS.map((c) => {
            const accent = c.color === "emerald" ? "#f59e0b" : "#fb923c";
            const isComplete = c.status === "Completed";
            return (
              <div
                key={c.name}
                className="card-lift"
                style={{
                  padding: "20px",
                  background: "#1c1914",
                  border: `1px solid ${isComplete ? accent + "44" : "#2e2a20"}`,
                }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
                  <span style={{ color: accent, fontSize: "1.1rem" }}>{c.icon}</span>
                  <span
                    className="font-mono"
                    style={{
                      fontSize: "0.65rem",
                      letterSpacing: "0.12em",
                      textTransform: "uppercase",
                      padding: "2px 8px",
                      border: `1px solid ${accent}44`,
                      color: accent,
                    }}
                  >
                    {c.status}
                  </span>
                </div>
                <h3 style={{ fontSize: "0.95rem", color: "#ede0cc", fontWeight: 600, marginBottom: "6px" }}>{c.name}</h3>
                <p className="font-mono" style={{ fontSize: "0.7rem", color: "#6b6457" }}>{c.eta}</p>
              </div>
            );
          })}
        </div>

        {/* Open University programme progress */}
        <div
          style={{
            marginTop: "48px",
            padding: "28px",
            background: "#1c1914",
            border: "1px solid #2e2a20",
            display: "flex",
            alignItems: "center",
            gap: "32px",
            flexWrap: "wrap",
          }}
        >
          <div>
            <p className="font-mono" style={{ fontSize: "0.65rem", color: "#6b6457", letterSpacing: "0.15em", marginBottom: "6px" }}>OPEN UNIVERSITY // KEY MODULES</p>
            <div style={{ display: "flex", gap: "32px", flexWrap: "wrap" }}>
              {[
                { k: "Networking", v: "✓" },
                { k: "Pen Testing", v: "✓" },
                { k: "Info Security", v: "✓" },
                { k: "Programming", v: "✓" },
              ].map(({ k, v }) => (
                <div key={k}>
                  <div className="font-mono" style={{ fontSize: "0.65rem", color: "#6b6457" }}>{k}</div>
                  <div className="font-mono" style={{ fontSize: "1.6rem", color: "#fb923c", fontWeight: 700 }}>{v}</div>
                </div>
              ))}
            </div>
          </div>
          <div style={{ flex: 1, display: "flex", justifyContent: "flex-end" }}>
            <a
              href="https://www.open.ac.uk/courses/cyber-security"
              target="_blank"
              rel="noopener noreferrer"
              className="font-mono"
              style={{
                padding: "10px 20px",
                border: "1px solid #fb923c",
                color: "#fb923c",
                textDecoration: "none",
                fontSize: "0.75rem",
                letterSpacing: "0.12em",
                textTransform: "uppercase",
                transition: "all 0.2s",
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = "#fb923c"; e.currentTarget.style.color = "#12100c"; }}
              onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; e.currentTarget.style.color = "#fb923c"; }}
            >
              View Programme →
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}

function ContactSection() {
  return (
    <section id="contact" style={{ padding: "100px 24px 60px", background: "#0e0c09", borderTop: "1px solid #2e2a20" }}>
      <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
        <SectionLabel>05 // Contact</SectionLabel>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "64px", alignItems: "start" }} className="two-col-grid">
          <div>
            <h2
              className="font-display"
              style={{ fontSize: "clamp(2rem, 5vw, 3rem)", fontWeight: 700, color: "#f5efe4", marginBottom: "16px" }}
            >
              Let's Talk Security
            </h2>
            <p style={{ color: "#7a7060", lineHeight: 1.8, marginBottom: "32px", fontSize: "0.95rem" }}>
              Open to SOC analyst roles, IT security support positions, and blue team
              opportunities across the UK. Response within 24 hours.
            </p>
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              <ContactRow icon="@" label="Email" value="elboatengmichael@gmail.com" href="mailto:elboatengmichael@gmail.com" />
              <ContactRow icon="⌥" label="LinkedIn" value="linkedin.com/in/michael-elboateng" href="https://www.linkedin.com/in/michael-elboateng" />
              <ContactRow icon="⌥" label="GitHub" value="github.com/elbmichael" href="https://github.com/elbmichael" />
              <ContactRow icon="◈" label="Location" value="Leeds, UK" href="#contact" />
            </div>
          </div>

          {/* Profile summary */}
          <div>
            <p className="font-mono" style={{ fontSize: "0.65rem", color: "#6b6457", letterSpacing: "0.15em", marginBottom: "12px" }}>
              PROFILE SUMMARY
            </p>
            <div
              style={{
                background: "#12100c",
                border: "1px solid #2e2a20",
                padding: "20px",
                color: "#a89880",
                fontSize: "0.88rem",
                lineHeight: 1.8,
              }}
            >
              Highly disciplined and analytical aspiring cybersecurity professional with a
              proven commitment to structured, continuous learning. Eager to transition
              transferable problem-solving skills into a dedicated security role, with a
              sharp focus on mitigating network vulnerabilities and defending digital
              infrastructure against evolving cyber threats.
            </div>
          </div>
        </div>

        {/* Footer strip */}
        <div
          style={{
            marginTop: "80px",
            paddingTop: "24px",
            borderTop: "1px solid #2e2a20",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: "16px",
          }}
        >
          <span className="font-mono" style={{ fontSize: "0.7rem", color: "#3a3428" }}>
            © 2026 Michael Elboateng Manu // Built for GitHub Pages
          </span>
          <span className="font-mono" style={{ fontSize: "0.7rem", color: "#3a3428" }}>
            <span style={{ color: "#f59e0b" }}>✓</span> Available for roles
          </span>
        </div>
      </div>
    </section>
  );
}

function ContactRow({ icon, label, value, href }: { icon: string; label: string; value: string; href: string }) {
  const [hovered, setHovered] = useState(false);
  return (
    <a
      href={href}
      target={href.startsWith("mailto") ? undefined : "_blank"}
      rel="noopener noreferrer"
      style={{
        display: "flex",
        alignItems: "center",
        gap: "14px",
        padding: "12px 16px",
        background: hovered ? "#221e16" : "#1c1914",
        border: `1px solid ${hovered ? "#f59e0b" : "#2e2a20"}`,
        textDecoration: "none",
        transition: "all 0.2s",
      }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      <span className="font-mono" style={{ color: "#f59e0b", fontSize: "0.9rem", width: "20px", textAlign: "center" }}>{icon}</span>
      <span className="font-mono" style={{ fontSize: "0.65rem", color: "#6b6457", letterSpacing: "0.12em", width: "70px" }}>{label.toUpperCase()}</span>
      <span style={{ color: "#a89880", fontSize: "0.85rem" }}>{value}</span>
    </a>
  );
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <p className="font-mono" style={{ fontSize: "0.68rem", letterSpacing: "0.2em", color: "#f59e0b", textTransform: "uppercase", marginBottom: "12px" }}>
      {children}
    </p>
  );
}

// ─── App ──────────────────────────────────────────────────────────────────────

export default function App() {
  return (
    <div className="scanline" style={{ minHeight: "100vh", background: "#12100c" }}>
      <style>{`
        @media (max-width: 900px) {
          .hidden-mobile { display: none !important; }
          .show-mobile { display: block !important; }
          .two-col-grid { grid-template-columns: 1fr !important; }
          .three-col-grid { grid-template-columns: 1fr !important; }
          .skills-grid { grid-template-columns: 1fr !important; }
        }
        @media (min-width: 901px) {
          .show-mobile { display: none !important; }
        }
      `}</style>
      <NavBar />
      <HeroSection />
      <SkillMatrix />
      <ProjectsSection />
      <LearningSection />
      <ContactSection />
    </div>
  );
}
